10    2023-10-07
    THIS LIVING REMINDER

Dilemma, confusion, This misleading intuition
Is the similarity real or is this a delusion
Angel eyes, hair, the convergence of height
Pretty nails, which to touch, are a delight

A plump abdomen really sweet to huggggggg
though i wont do that or my grave will be duggggggg
The one thing amiss is that sweetsie sound
A bliss to the ears which spins my head around

Almost all that what i still craved
Set the sirens blaring, I need to be saved
Hope her hands dont fit like hers did 
Hope something happens that makes her mid


    2023-10-27
    I GUESS THIS PERSON DOES MEAN ENOUGH TO ME TO WRITE STH

This sensation, What could be this feeling in my heart?
These butterflies in my stomach, were they there from the start?
My throat goes completely numb, my brain just splits apart
Can't convey, can't commit, it eats me up like a tart

Can't converse, can't confide, helpless as a mute
It's a hapless situation, you just cannot refute
Thats not the only qualm, cuz even though she's cute
If the seed did grow, it might not bear a fruit

Is it cause i miss her, or the feeling's anew
Or tis a fling to fly away, i wish i knew
Too many variables, the gammas, the mu
The uncertainity, of what would ensue

Trying hard not to fight myself for this
Avoiding the pain after the ephimeral bliss
Night full of stars that ends in a kiss
Is not worth it unless she will be your miss

Still, i crave that closeness with her
Having someone to love, cherish, fonder
Know i shouldnt, but my heart does ponder
Any way, is there, to be together forever?


    Oka. this is going to be a huge project, but a confession in a tiered acrostic (this is gonna be hard asf, but worth it if i gain a friend for life)!
    start: 2023-10-28
    end:   2023-10-31

    Inamorata!!

Inamorata!!

Look Utterly Cute ,I Dream Loving You
Obsessed, Fighting For Eschewing Rue
Venting Out Wholehearted Sentiments
Eventually, The Envelop Rises, Nullifying All Laments

You're Eloquent, A Really Nosy, Indomitable, Noteworthy Girl 
One Cherishes Ecstacy, A Newfound Swirl
Unseen Nature Showed Extremely Enigmatic Nirvana


    this odd one out 

These cutesie eyes, this cutesie pink
This sweetsie smile, makes my heart sink
just like your earphones, our hearts have a link
just like your specs, our faces twink

sweeter than the icecream you hold
sweeter than Polar's chocolate road
these bulging blithely like a toad
your cheeks express our love so bold

hair unkempt, but still a beauty
a toddler toddling at pattanagere
bugged your robot into sayin EEEE
with this pic that screams "WE"

    2023-11-16

this broken, shattered, crushed heart
once belonged to a boy who wouldnt depart
from his dream about a girl so cute
angels themselves wouldnt refute

Their bond was unbreakable, he wasnt ever distraught
didnt think he would have to say, "or so i thought"
Their love was pure and telepathy unmatched
they were repeatedly severed, and kept getting patched

He wanted her, and no one else he longed
made sure, that one person, he never wronged
but fate had something else in store
a dickhead barged and casually stole

is the legend of love that superficial
so weak you doubt it was artificial
a simple action taints your mind
and you screw a pact never signed

"roaming hands around one another"
thrusting the knife in his heart further
if he found this boy on the loose
he would meet his end on the noose

there's no pain, there's will to die
A will to perish without a cry
The utter trust decimated
that mendacity deracinated

these 7 stanzas speak his pain
those hugs and kisses in the rain
those bugs and misses bygone
now he'd rather be alone

    start: 2023-11-14
    end:

prospering makes you alone
people change over time
winter, spring, summer, autumn, winter

The snow clad plains, the grayscale view
a spell of chlorine, no color or hue
the cold hatred, the freezing eyes
of people sick of his inept lies

It rains and hails, he tries and fails
both skill and luck, like heads and tails
against his fate, every day and date
misfit's manifesto, drive out this hate

he might be dull, he might be dumb
even with the frost, the pain wont numb
but to this plight, he wont succumb
he will reform, rise from the scum 


    start: 2024-01-22

my feelings for you are religious,
to kill them is sacrilegious,
love is'nt something so jejune,
that a simple reprog can prune,
it is'nt my style to do blank verses,
my heart rhymes even in bits and pieces.

today, the eyes that dilated for you,
did let a lil bit of water through,
even phone calls are like a spell cast,
God knows what i could to to make us last,
pardon, but the scar of affection seldom heals,
I'll keep talking to you through these short spiels.

Please go fly and find more love,
find someone who can be your dove,
but don't give yourself to pure lust,
you dont belong with some tramps in the dust,
having vented, I'll conclude this 6 line rhyme,
I'll live with a heart that is'nt half mine.


    Don't even ask me why
    start: 2024-02-08
    end: 2024-07-23

Hey!
Ms. Bindra, Happy 19th birthday
an occasion on a random wednesday
let us all count down to portray
all the reasons to dance the day away

Ten!
I see a Leo, a lioness in her den 
with a face as expressive as this pen 
expected of a fire sign to hold the adrenaline
and the fire to turn one to 'n'

Nine!
lets keep continuing this rhyme
its trivial to keep any poem a dime
Paradise indeed Lost, makes me whine
poem no rhyme, is gold no shine

Eight!
there is no Rakshit to make you wait
plus you're at home, so you cannot be late
maybe check out books throughout the state
maybe pizzas we love or softies we dont hate

Seven!
the shlope that could be a heaven
where we threw the plane for 9-11
slowly witnessed the friendship deepen
to the point the poet picked the pen

Six!
There happened to be some sorta jinx
but theres nothing that time can't fix
the hands turn, wipe away the thorny sticks
start anew, cause losing friends pricks

Five!
A complete year in this amity hive
Even gave anmol a chance to drive
The few times we did connive
was better than some concert live

Four!
there will be plot twists in the lore
but keep aiming at the top floor
keep pushing, cause it's perserverences' door
that will grant access to the success store

Three!
You have a day to be completely free
so maybe indulge in a shopping spree
maybe try some delicious entree
and do whatever makes you glee

Two!
A day made just for you
so make sure to leave no rue
but I trusted you yaar, believe me it's true
from red to violet with yellow and blue

One!
the last two stanzas after the damage was done
but guess theres no avoiding what fate has spun
so let me conjure in the blazing sun
the last birthday wish to an important one. 

Happy birthday!

Now, Ms. Leo, dont just act like a Cancer
dont bury me in the silence of the answer


    DDG
    start : 2024-02-13

Happy birthday Titli ddg
stay happy, buzzing as a bee 
fearless, a skydive
and the best sister just turned 35


    eeeeeeeeeeeeeeeeeeeeeeeee
    date : 2024-07-28

things to remember you by 

Hi!
a beautiful september and a painful july
a tadsy bit of intel about e and pi
a bugged DBMS in which no flaws lie 
youve left so many things to remember you by

*sigh* 
one truthful promise in a night full of lies 
climbing two floors to greet two sleepy eyes
moments one can cherish till the latter dies
youve left so many things to remember you by

laying on the terrace while looking at the sky 
movies to watch while having waiwai
childish conscience with the XXXL bye
youve left so many things to remember you by

we might never meet again and it makes me cry 
we never made that cover of him and I
but as a wonderful friend and a toddler, oh my
youve left so many things to remember you by

    birthday poem 

I know it's been a while since my paper was struck by quill
Let this be an attempt to show the the issue is not skill
I was blessed to meet my Best Friend my ride or die
and to say that I'm not grateful would be a blatant lie
Thus I proudly declare on this 25th May
The 19th birthday of a girl so gay

Happy Birthday Ria, you are indeed a gem
a pearl, so cute, ineffable by a pen
I know it always feels like I look down on you often
But know that tis my way of exposing a heart thats soften
Still if you think that this much rhyme is all a robot can manage
Save your expectation, it's something I'll damage

I have a hanker to pamper this ranker that anchors me
to the ground, I'm wound to your sound all around me
I hear you, I feel cray, my brain stuck on replay
dizzy and delusional, can't differentiate like Dirichlet
is it real or is it fake, is it a mirage or a lake?
forget it, just celebrate the awaited day with a cake

You know that you really live that life people consider a myth
and I expect you to take it to the next level on this day 25th 
A day to enjoy, rejoice, share
A day to spend with the people that care
and if you won't mind, here's a dare
Reach for the sky, and show you can fare

Life is way too short to take it slow
so dance in ecstacy as the candles blow
Take out your hairstick, let those long locks sway
those slippers squeak as you dance the day away
be happy, no matter what the strife
just joke about it and say sed lyf

For me you'll be that Cutesie Buggggg
The one Arka called to debuggggg
You're deft enough to LaTeX now
and teach it to Ashu, just wow!
But please you couple quit OverLeaf
neovim has NERDTree so why work with weaf(child pronunciation)

for now I'll suggest what to so today
Be the RandomRia you were always
hop in a bus, roam around adajan and eat some popcorn
get some mehndi and buy beautiful scrunchies you can adorn
I already know, from go to woah
You'll squezze the joy out from this day so

I'll talk about something else, change the topic
I'll try not to come across as psychotic
But miss ya yaar, I miss the days
I would see those eyes, that smile, those nails 
I still feel that care, that concern we share
for each other, being the inseperable pair

The pair that shared kettles of Wai-Wai
The pair watched movies without the Wi-Fi
The pair that enjoyed that spicy panipuri
The pair that cherished that dosa at pattanagere
countless other anecdotes we hold
that proves our doting love so bold

But even if that bond is physically severed
I'll text you everyday, and prove I cared
for now, go say, "Bhaiya theekha jyada rakhna"
mujhe nahi pata kaise khaati hai aisa chakhna
so now I conclude this piece of my heart to you
A cute toddler girl, and a friend so true.


    Reply poem

The feeling's mutual, I am blessed to have you
For the poem you wrote me, I thank you
The morse was decoded in like three hours
With breaks in between for tears and laughs

You don't just simply pamper me, 
You respect me and deeply, truly care for me
We've gone through ups and downs, hits and misses
It hasn't been just roses, rainbows, hugs and kisses

You hear my sound all around you
And wherever I go, all that's there on my mind's you
So yes, what we have is real, not fake
And I so wish you were here to share the cake

Past few days have been a bit rough
With mental stress or cold and cough
But now I accept your indirect dare
I'll joke and say sed lyf, no matter the nightmare

Also, you're right, life's too short to think
We should just decorate our faces with a grin
Let the wind decide which way our hair flows in
Why worry about life when we can just spin? 

From keyboard shortcuts to latex
From software stuff to phone specs
There's so much I've learnt from you, 
And for that I'm always indebted to you

But don't get me wrong, seriously
How in a bday poem, can you bring up nvim, overleaf? 
It's hilarious to think yeh banda
Kahin pe bhi robotgiri hai kar sakta😅🤣 

Coming to your to do list for today
Since I'm on a trip it might get a bit delayed
But it is a very fun one indeed, and yes
I'll get mehndi and scrunchies that match my dresses

From the 'natkhat' eyes while toyifying
To the 'sukoon bhari' eyes while just casually lying 
ISI won't be the same for me without you
It pains to see you leave, I'll miss you dearly too

You gave me a dare, I'll give you one too
Don't come online at 10 pm one night, I dare you
Write it in your head; in bold, italic, underlined font
HELL HATH NO FURY LIKE A WOMAN SCORNED

On this birthday, I hope you promise me
Talk to me daily and never betray me
Ps. Panipuri ka pani tikha hi hoga
Kyunki main bhi hun ek tikhi pataka 🤣 (ok, panchat)




    eeeeeeeeeeeeeeeeeeeeeeee


I wish it wasn't this way
But I can't help but ask you to stay

Stay, for the kisses and cuddles
Stay, I'll share wai wai noodles

Stay, we haven't been on enough dates
You can curse me while having spicy panipuri plates

Stay, you're the one in all my dreams
Cringe maybe, but you are sweeter than ice cream

Stay, let's actually finish our watchlist
Stay, maybe there's a movie we missed

Stay, let's beat our scores in minesweeper
Wait, did we forget the 36th operius sector? 

Hey, do you remember Mango and Shooting Star? 
Stay, let's explore all 31 flavours at BR

The world can't say I'm not a child
Yet only you know the monster in me's wild 

Stay, I want to see a healed diku
'Stay', says a very gloomy miku

Stay and laugh on my knowledge in computers
Stay, my robot, with your annoying little buggggg

Stay with me through the night
Stay, it can't be that hard, right?

Stay, we won't ever again waver
Stay, ab ruk bhi ja, dikhaye bade tevar

Stay, we'll share laughs and tears
Stay, we'll get through all our fears

Stay for the telepathy that we share
Stay, 'cuz this distance we can't bear

Stay with me and you shall see
I'll always be the same, your ghanjedi

    fingers crossed...
    date: 2024-10-26 

I know you're cross, but please bear
I seek to understand, 'cuz I do care
There are few true friends; they aren't plenty
Especially this one girl yet to turn twenty
To lose you would fill my heart with rue 
I plead you to please think this through 

Already many memories that I have with you 
Numerous things that we've been through 
From 401 to 403
From Elante to CP
From the indoor to the shlope 
This ain't something with which I can cope 

The fresher's night, tying your sandals
walking to the gurudwara, breaking your ankles
The physics lab, that one presentation
Cheating in exams without lamentation
I'll take all your scorn and scoff 
Just please, I beg, don't put us off

I crossed the line, and I apologize
All my wrongs, I do realize
I kneel before you and beg for mercy
I ask of you not to curse me 
Please don't break off on a whim 
and I'll stick with you through thick and thin

    Pleaseeeee
    date: 2024-12-10

Daybreak 

writing through this night, hoping things go right
being friends with you has been a true delight 
eighteen months in, I wish we never faltered
because somewhere along the way, my feelings altered

At first, I actually wanted a friend 
just someone to talk to till the end 
we started talking and even sat together 
your heart turned my evening sky heather

When you first asked to sit with me, I was reluctant 
You were just a friend, and I was reticent 
but after knowing you, my mind wasn't the same 
you had a heart of gold, just like your name 

no thing is perfect, we had our rough patches 
but some bonds cannot be burnt by matches 
you're cute, you're graceful, you're svelte
is this love is to be followed, or only felt

No matter what happens after I confess 
This daybreak will be a new start nontheless 
So no hiding behind some april fools anymore 
allow me to know yachiru better, down to her core 
